version: '3.4'

services:
  BettingGame.usermanagement.web:
    image: bettinggameusermanagementweb
    build:
      context: .
      dockerfile: BettingGame.UserManagement.Web/Dockerfile
    depends_on:
      - mongodb
    links:
      - "mongodb:db"

  BettingGame.betting.web:
    image: bettinggamebettingweb
    build:
      context: .
      dockerfile: BettingGame.Betting.Web/Dockerfile
    depends_on:
     - mongodb
    links:
      - "mongodb:db"

  BettingGame.tournament.web:
    image: bettinggametournamentweb
    build:
      context: .
      dockerfile: BettingGame.Tournament.Web/Dockerfile
    depends_on:
      - BettingGame.betting.web # Inform about game results.
      - mongodb
    environment:
       BettingBaseUrl: http://betting:80
    links:
      - "mongodb:db"
      - "BettingGame.betting.web:betting"

  BettingGame.ranking.web:
    image: bettinggamerankingweb
    build:
      context: .
      dockerfile: BettingGame.Ranking.Web/Dockerfile
    depends_on:
      - BettingGame.betting.web # The schedule task which gets the ranking.
      - BettingGame.usermanagement.web # The schedule task which gets the ranking.
      - mongodb
    environment:
      BettingBaseUrl: http://betting:80
      UserManagementBaseUrl: http://usermanagement:80
    links:
      - "mongodb:db"
      - "BettingGame.betting.web:betting"
      - "BettingGame.usermanagement.web:usermanagement"

  mongodb:
      image: mongo
      ports:
          - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181